project:
  name: SpringBootApplication
  description: A Spring MVC project with Thymeleaf
  groupId: com.springframework
  artifactId: sample
  version: 1.0.0
  output_destination: /Users/deeptmodi/Desktop/Student1

api_key: "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"
java:
  version: 11

server:
  port: 8080

java_source_folder:
  - origin: src
    destination: src/main/java

jsp_source_folder:
  - origin: webapp
    destination: src/main/resources/template

css_source_folder:
  - origin: webapp/css
    destination: src/main/resources/static

  - origin: dummy
    destination: src/main/resources/static

images_source_folder:
  - origin: webapp/images
    destination: src/main/resources/images

  - origin: dummy
    destination: dummy

other_source_folder: # For direct copy
  - origin: webapp/videos
    destination: src/main/resources/videos

  - origin: dummy
    destination: dummy

dependencies:
  - spring-boot-starter-web
  - spring-boot-starter-thymeleaf
  -

database:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mydatabase
  username: your_username
  password: your_password

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<database_name>
    username: <database_user>
    password: <password>

git:
  url: https://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@github.com/deeptmodi/servlet_springboot_migration.git
  username: deeptmodi
  email: deeptmodi@deloitte.com
