"""
Django settings for ejb_spring_boot project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv

# Load variables from .env file

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yla*q-n*c-ec1*f)cfshhdsokdjbq*y3wo3m3!ezj#gp%!fu#)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ejb_spring_boot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'ejb_spring_boot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

LOG_PROMPT = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://ejb-springboot-preprod-urtjok3rza-wl.a.run.app',
    'https://ejb-springboot-urtjok3rza-wl.a.run.app',
    'https://hashedin-poc-fe-urtjok3rza-wl.a.run.app',
    'https://hashedin-poc-fe-preprod-urtjok3rza-wl.a.run.app',
    'https://genai-preprod-3446x4g1.wl.gateway.dev',
    'https://gen-ai-3446x4g1.wl.gateway.dev',
    'https://hashedin-poc-fe-preprod-urtjok3rza-uw.a.run.app',
    'https://hashedin-poc-fe-urtjok3rza-uw.a.run.app',
    'https://genai.hashedin.com',
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'https://ejb-springboot-preprod-urtjok3rza-wl.a.run.app',
    'https://ejb-springboot-urtjok3rza-wl.a.run.app',
    'https://hashedin-poc-fe-urtjok3rza-wl.a.run.app',
    'https://hashedin-poc-fe-preprod-urtjok3rza-wl.a.run.app',
    'https://genai-preprod-3446x4g1.wl.gateway.dev',
    'https://gen-ai-3446x4g1.wl.gateway.dev',
    'https://hashedin-poc-fe-preprod-urtjok3rza-uw.a.run.app',
    'https://hashedin-poc-fe-urtjok3rza-uw.a.run.app',
    'https://genai.hashedin.com',
]
